---
title: "Text-Network Analysis of White & Black Soldiers"
description: "This page provides sentiment of race relations from Survey 32."
tags: ["R", "sna", "race relations"]
weight: 1
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
---

```{css, echo=FALSE}
/* this chunnk of code centers all of the headings */
h1, h2, h3 {
  text-align: center;
}
```


```{r setup, include=FALSE, message=FALSE, warning=FALSE}
rm(list = ls()) 

knitr::opts_chunk$set(echo = F, fig.width = 8, fig.height = 6)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) ;

library(stringi)
library(data.table)
library(tidyverse)
library(tidytext)
library(textstem)
library(readxl)
library(SnowballC)
library(rvest)
library(tm)
library(topicmodels)
library(tidyr)
library(textdata)
library(wordcloud)
library(RColorBrewer)
library(igraph)
library(ggraph)
library(widyr)
library(stringr)
library(networkD3)
library(RColorBrewer)
library(usmap) 
library(viridis)
library(ggplot2)
library(BTM)
library(udpipe)
library(networkD3)
library(topicmodels)
library(concaveman)
library(textplot)
library(stopwords)
library(dplyr)
# to install ggradar, run the line commented out below
#devtools::install_github("ricardo-bion/ggradar", dependencies = TRUE)
#library(ggradar)
library(tibble)
library(scales)
library(fmsb)
library(sentimentr)
library(syn)

data(stop_words)
colors <- c("#e57200", "#232d4b")
collapse <- fread("/sfs/qumulo/qhome/kb7hp/git/american-soldier/data/dictionary/collapse_words.csv", sep = ",")
#collapse <- fread("~/git/dspg2020amsoldier/data/dictionary/collapse_words.csv", sep = ",")
collapse <- mutate(collapse, original = paste("\\b", original,"\\b", sep = "")) #so that stringr doesn't pick up on instances where it is part of another word
#replace with collapsed words
source(here::here("src", "load_data.R"))
source(here::here("src", "sentiment_analysis.R"))
source(here::here("src", "word_selection.R"))

data$long <- stri_replace_all_regex(data$long, collapse$original, collapse$collapse_union, vectorize_all = FALSE)
data$outfits_comment <- stri_replace_all_regex(data$outfits_comment, collapse$original, collapse$collapse_union, vectorize_all = FALSE)

S32N <- filter(data, racial_group == "black")
S32W <- filter(data, racial_group == "white")

text77_df <- tibble(row = 1:nrow(S32W), text = S32W$outfits_comment, outfits = S32W$outfits) #Written response to "should soldiers be in separate outfits?"
text78_df <- tibble(row = 1:nrow(S32W), text = S32W$long) #Written response on overall thoughts on the survey
textn_df <- tibble(row = 1:nrow(S32N), text = S32N$long)
```

# for white soldiers we have:
1. their survey response for the outfits question
2. their commentary on the outfits question
3. a longer commentary question on the general survey

# for black soldiers we have: 
1. a longer commentary question on the general survey

```{r unions, echo = FALSE, message=FALSE, warning=FALSE}

# this takes the long response for black soldiers and tokenizes the df 
row_n_words <- textn_df %>%
  mutate(section = row_number()) %>%
  filter(section > 0) %>%
  mutate(text = ifelse(str_detect(text, "u.s."), "usa", text)) %>%
  mutate(text = ifelse(str_detect(text, "don⊙t"), "don't", text)) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word) %>%
  mutate(word= textstem::lemmatize_words(word)) %>%
  mutate(word= wordStem(word))

# cleans all of the stemming to make the visuals more interpretable 
row_n_words <- row_n_words %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(bu)\\b"), "bus", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(segreg)\\b"), "segregation", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(discrimin)\\b"), "discrimination", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(separ)\\b"), "separate", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(divis)\\b"), "division", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(emancip)\\b"), "emancipation", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(democraci)\\b"), "democracy", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(privedlag|privileg)\\b"), "privilege", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(realiz)\\b"), "realize", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(blackmal)\\b"), "black-man", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(whitemal)\\b"), "white-man", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(blackfemal)\\b"), "black-woman", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(whitefemal)\\b"), "white-woman", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(manpow)\\b"), "manpower", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(southern)\\b"), "south", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(northern)\\b"), "north", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(american|u.s.a|usa)\\b"), "america", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(approv)\\b"), "approve", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(forc)\\b"), "force", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(ignor)\\b"), "ignore", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(germani)\\b"), "german", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(jap)\\b"), "japan", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(divid)\\b"), "divide", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(hatr)\\b"), "hatred", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(rememb)\\b"), "remember", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(liberti)\\b"), "liberty", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(px|p.x)\\b"), "post-exchange", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(polic)\\b"), "police", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(mp|m.p)\\b"), "military-police", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(educ)\\b"), "educate", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(intellig)\\b"), "intelligence", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(defens)\\b"), "defense", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(practic)\\b"), "practice", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(volunt)\\b"), "volunteer", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(futur)\\b"), "future", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(enemi)\\b"), "enemies", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(polici)\\b"), "policy", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(constitut)\\b"), "constitution", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(countri)\\b"), "country", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(armi)\\b"), "army", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(offic)\\b"), "office", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(servic)\\b"), "service", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(dai)\\b"), "day", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(chanc)\\b"), "chance", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(compani)\\b"), "company", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(condit)\\b"), "condition", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(leav)\\b"), "leave", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(pai)\\b"), "pay", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(famili)\\b"), "family", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(abil)\\b"), "ability", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(chang)\\b"), "change", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(prejudic)\\b"), "prejudice", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(monei)\\b"), "money", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(not't)\\b"), "not", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(suppos)\\b"), "suppose", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(victori)\\b"), "victory", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(opportun)\\b"), "opportunity", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(serv)\\b"), "serve", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(troubl)\\b"), "trouble", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(recreat)\\b"), "recreate", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(advanc)\\b"), "advance", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(peopl)\\b"), "people", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(marri)\\b"), "marry", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(prai)\\b"), "pray", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(ag)\\b"), "age", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(receiv)\\b"), "receive", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(promot)\\b"), "promotion", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(mechan)\\b"), "mechanic", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(discharg)\\b"), "discharge", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(infrantri)\\b"), "infrantry", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(complet)\\b"), "complete", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(moral)\\b"), "morale", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(carri)\\b"), "carry", word)) #%>% 
  #count(word) %>% 
  #arrange(-n)

# count words co-occuring within sections
word_pairs_n <- row_n_words %>%
  pairwise_count(word, section, sort = TRUE)

# filters the words not freq used 
word_cors_n <- row_n_words %>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, section, sort = TRUE) %>%
  filter(correlation > .1)

# de-duplicates the edgelist
remove_dups <- igraph::simplify(graph.data.frame(word_cors_n, directed = FALSE), 
                              edge.attr.comb = igraph_opt("edge.attr.comb"),
                              remove.loops = FALSE)
remove_dups <- data.frame(as_edgelist(remove_dups, names = TRUE))

corr_edgelist <- remove_dups %>% 
  rename(item1 = X1, item2 = X2) %>% 
  left_join(word_cors_n, by = c("item1", "item2")) %>% 
  arrange(-correlation)

# removes the numbers 
number_list <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15")
corr_edgelist_n <- corr_edgelist %>% 
  rename(source = item1, target = item2, weight = correlation) %>%  
  filter(!(source %in% number_list) & !(target %in% number_list)) 

# quick look at the network 
set.seed(2016)
corr_edgelist_n %>%
  filter(weight > .1) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = weight), show.legend = TRUE) +
  geom_node_point(color = "#E57200", size = 5) +
  #geom_node_text(aes(label = name), repel = TRUE) +
  ggtitle("Co-Occurences of Words from Black Soldiers' Long \nResponses at the 10% Threshold") +
  theme_void()

write_csv(corr_edgelist_n, "/sfs/qumulo/qhome/kb7hp/git/american-soldier/data/post_dspg/cooc32long_n.csv")

```


```{r unions, echo = FALSE, message=FALSE, warning=FALSE}

# this takes the long response for black soldiers and tokenizes the df 
row_n_words <- text78_df %>%
  mutate(section = row_number()) %>%
  filter(section > 0) %>%
  mutate(text = ifelse(str_detect(text, "u.s."), "usa", text)) %>%
  mutate(text = ifelse(str_detect(text, "don⊙t"), "don't", text)) %>%
  unnest_tokens(word, text) %>%
  filter(!word %in% stop_words$word) %>%
  mutate(word= textstem::lemmatize_words(word)) %>%
  mutate(word= wordStem(word))

# cleans all of the stemming to make the visuals more interpretable 
row_n_words <- row_n_words %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(bu)\\b"), "bus", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(segreg)\\b"), "segregation", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(discrimin)\\b"), "discrimination", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(separ)\\b"), "separate", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(divis)\\b"), "division", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(emancip)\\b"), "emancipation", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(democraci)\\b"), "democracy", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(privedlag|privileg)\\b"), "privilege", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(realiz)\\b"), "realize", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(blackmal)\\b"), "black-man", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(whitemal)\\b"), "white-man", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(blackfemal)\\b"), "black-woman", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(whitefemal)\\b"), "white-woman", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(manpow)\\b"), "manpower", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(southern)\\b"), "south", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(northern)\\b"), "north", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(american|u.s.a|usa)\\b"), "america", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(approv)\\b"), "approve", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(forc)\\b"), "force", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(ignor)\\b"), "ignore", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(germani)\\b"), "german", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(jap)\\b"), "japan", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(divid)\\b"), "divide", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(hatr)\\b"), "hatred", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(rememb)\\b"), "remember", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(liberti)\\b"), "liberty", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(px|p.x)\\b"), "post-exchange", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(polic)\\b"), "police", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(mp|m.p)\\b"), "military-police", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(educ)\\b"), "educate", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(intellig)\\b"), "intelligence", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(defens)\\b"), "defense", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(practic)\\b"), "practice", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(volunt)\\b"), "volunteer", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(futur)\\b"), "future", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(enemi)\\b"), "enemies", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(polici)\\b"), "policy", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(constitut)\\b"), "constitution", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(countri)\\b"), "country", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(armi)\\b"), "army", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(offic)\\b"), "office", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(servic)\\b"), "service", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(dai)\\b"), "day", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(chanc)\\b"), "chance", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(compani)\\b"), "company", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(condit)\\b"), "condition", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(leav)\\b"), "leave", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(pai)\\b"), "pay", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(famili)\\b"), "family", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(abil)\\b"), "ability", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(chang)\\b"), "change", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(prejudic)\\b"), "prejudice", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(monei)\\b"), "money", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(not't)\\b"), "not", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(suppos)\\b"), "suppose", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(victori)\\b"), "victory", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(opportun)\\b"), "opportunity", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(serv)\\b"), "serve", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(troubl)\\b"), "trouble", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(recreat)\\b"), "recreate", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(advanc)\\b"), "advance", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(peopl)\\b"), "people", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(marri)\\b"), "marry", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(prai)\\b"), "pray", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(ag)\\b"), "age", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(receiv)\\b"), "receive", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(promot)\\b"), "promotion", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(mechan)\\b"), "mechanic", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(discharg)\\b"), "discharge", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(infrantri)\\b"), "infrantry", word)) %>% 
  mutate(word = ifelse(str_detect(word, "\\b(?i)(complet)\\b"), "complete", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(moral)\\b"), "morale", word)) %>%
  mutate(word = ifelse(str_detect(word, "\\b(?i)(carri)\\b"), "carry", word)) #%>% 
  #count(word) %>% 
  #arrange(-n)

# count words co-occuring within sections
word_pairs_n <- row_n_words %>%
  pairwise_count(word, section, sort = TRUE)

# filters the words not freq used 
word_cors_n <- row_n_words %>%
  group_by(word) %>%
  filter(n() >= 20) %>%
  pairwise_cor(word, section, sort = TRUE) %>%
  filter(correlation > .1)

# de-duplicates the edgelist
remove_dups <- igraph::simplify(graph.data.frame(word_cors_n, directed = FALSE), 
                              edge.attr.comb = igraph_opt("edge.attr.comb"),
                              remove.loops = FALSE)
remove_dups <- data.frame(as_edgelist(remove_dups, names = TRUE))

corr_edgelist <- remove_dups %>% 
  rename(item1 = X1, item2 = X2) %>% 
  left_join(word_cors_n, by = c("item1", "item2")) %>% 
  arrange(-correlation)

# removes the numbers 
number_list <- c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15")
corr_edgelist_w <- corr_edgelist %>% 
  rename(source = item1, target = item2, weight = correlation) %>%  
  filter(!(source %in% number_list) & !(target %in% number_list)) 

# quick look at the network 
set.seed(2016)
corr_edgelist_w %>%
  filter(weight > .1) %>%
  graph_from_data_frame() %>%
  ggraph(layout = "fr") +
  geom_edge_link(aes(edge_alpha = weight), show.legend = TRUE) +
  geom_node_point(color = "#E57200", size = 5) +
  #geom_node_text(aes(label = name), repel = TRUE) +
  ggtitle("Co-Occurences of Words from Black Soldiers' Long \nResponses at the 10% Threshold") +
  theme_void()

write_csv(corr_edgelist_w, "/sfs/qumulo/qhome/kb7hp/git/american-soldier/data/post_dspg/cooc32long_w.csv")

```

```{r}

comb_edgelist_n <- corr_edgelist_n %>% 
  mutate(group = "black")

comb_edgelist_w <- corr_edgelist_w %>% 
  mutate(group = "white")

#comb_edgelist_nw 

comb_edgelist_wn <- comb_edgelist_n %>% 
  bind_rows(comb_edgelist_w) %>% 
  arrange(-weight)

write_csv(comb_edgelist_wn, "/sfs/qumulo/qhome/kb7hp/git/american-soldier/data/post_dspg/cooc32long_nw.csv")

```





